# docker-compose.yml

version: '3.10'

services:
  prefect-agent:
    build:
      context: .
      platforms: linux/arm64
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - team5

networks:
  team5:
    external: True
