# .github/workflows/prefect-cicd.yaml

name: Prefect CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker buildx build --platform linux/arm64 -t myapp .

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: myapp:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions - build
        fields: repo,commit,message,author
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/docker/stock/"

    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/docker/stock
          echo "APP_KEY=${{ secrets.APP_KEY }}" > .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
          echo "HTS_ID=${{ secrets.HTS_ID }}" >> .env
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
          echo "PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}" >> .env
          docker-compose down --rmi all
          docker-compose build --platform linux/arm64
          docker-compose up -d

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions - deploy
        fields: repo,commit,message,author
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()

  prefect:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Export PREFECT_API_URL
      run: echo "PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}" > .env

    - name: Verify PREFECT_API_URL
      run: cat .env

    - name: Run Prefect Flow Registration Script
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PYTHONPATH: .
      run: python flow.py

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions - prefect
        fields: repo,commit,message,author
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
